---
- name: Configurar permisos NOPASSWD para el menú interactivo
  hosts: all
  become: yes
  gather_facts: false
  vars:
    usuario_admin: "admin"
  tasks:
    - name: Crear regla en /etc/sudoers.d/ para comandos específicos del menú
      ansible.builtin.copy:
        dest: "/etc/sudoers.d/ansible_menu_commands"
        content: |
          # Permitir al usuario del menú apagar, reiniciar y ejecutar el script sin contraseña
          {{ usuario_admin }} ALL=(ALL) NOPASSWD: /sbin/shutdown, /sbin/reboot, /usr/bin/systemctl reboot, /usr/bin/systemctl poweroff, /home/admin/labos/firewalls/conexion.sh, /etc/psico/fw_conexion.sh
        mode: '0440'
        validate: '/usr/sbin/visudo -cf %s'

    - name: Asegurar que el script viejo tenga permisos de ejecución
      ansible.builtin.file:
        path: /home/admin/labos/firewalls/conexion.sh
        mode: '0755'
      ignore_errors: true

    - name: Asegurar que el script nuevo tenga permisos de ejecución
      ansible.builtin.file:
        path: /etc/psico/fw_conexion.sh
        owner: root
        group: psico
        mode: '0770'
      ignore_errors: true
